-- Add new values to the HomeArea enum
ALTER TYPE "HomeArea" ADD VALUE IF NOT EXISTS 'LABEL_FACER';
ALTER TYPE "HomeArea" ADD VALUE IF NOT EXISTS 'SCANNER';
ALTER TYPE "HomeArea" ADD VALUE IF NOT EXISTS 'SPLITTER';
