-- Add new values to the HomeArea enum (idempotent, skip if enum doesn't exist)
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'HomeArea') THEN
    BEGIN ALTER TYPE "HomeArea" ADD VALUE IF NOT EXISTS 'LABEL_FACER'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER TYPE "HomeArea" ADD VALUE IF NOT EXISTS 'SCANNER'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN ALTER TYPE "HomeArea" ADD VALUE IF NOT EXISTS 'SPLITTER'; EXCEPTION WHEN OTHERS THEN NULL; END;
  END IF;
END $$;
